import * as React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { KeyRound, ArrowLeft, ShieldAlert } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { ROUTES } from '@/config/routes';

export const MfaPage: React.FC = () => {
  const navigate = useNavigate();
  const [otp, setOtp] = React.useState('');
  const [message, setMessage] = React.useState<string | null>(null);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    setMessage('Multi-Factor Authentication (OTP) endpoint contract is pending finalization. Please check back shortly.');
  };

  return (
    <div className="relative flex min-h-screen items-center justify-center p-4 overflow-hidden bg-background">
      <div className="w-full max-w-md space-y-6 relative z-10 animate-fade-in">
        <Card className="border-border/80 bg-card/80 backdrop-blur-xl shadow-2xl">
          <CardHeader className="text-center pb-2">
            <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-2xl border border-indigo-500/30 bg-indigo-600/20 text-indigo-400">
              <KeyRound className="h-6 w-6" />
            </div>
            <CardTitle className="text-xl font-bold">Two-Factor Authentication</CardTitle>
            <CardDescription>
              Enter the 6-digit security code generated by your authenticator app.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 pt-2">
            {message && (
              <div className="flex items-start space-x-2.5 rounded-lg border border-indigo-800/40 bg-indigo-950/40 p-3 text-xs text-indigo-200">
                <ShieldAlert className="h-4 w-4 shrink-0 text-indigo-400 mt-0.5" />
                <span>{message}</span>
              </div>
            )}

            <form onSubmit={handleVerify} className="space-y-4">
              <Input
                label="Verification Code"
                type="text"
                placeholder="123456"
                maxLength={6}
                value={otp}
                onChange={(e) => setOtp(e.target.value.replace(/\D/g, ''))}
                className="text-center tracking-widest text-lg font-mono"
              />

              <Button type="submit" className="w-full" size="lg">
                Verify Code (Placeholder)
              </Button>
            </form>

            <div className="pt-2 text-center">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => navigate(ROUTES.LOGIN)}
                leftIcon={<ArrowLeft className="h-4 w-4" />}
              >
                Back to Login
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
